### ISSUE TITLE
Refactor to meet checklist

### ISSUE THREAD

**Issue by djbowen95** [djbowen95/CatComplaints#6]
Not sure if there will be anything here - but wanted to keep it as an issue. Checklist: 

- [ ] Set up a single web page
- [ ] Have a header and footer
- [ ] Have an image with a caption
- [ ] Have a contact form
- [ ] Have a 'polished' UI

And:
- [ ] Use Semantic HTML
- [ ] Make sure I use universal, element and class selectors
- [ ] Must use three colours
- [ ] Must use one font / font family
- [ ] Must have at least two different heading elements
- [ ] Header must be fixed to the top of the page
- [ ] Nav bar must have three links
- [ ] One of those links must be 'contact'
- [ ] Contact form must have input for 'name' and 'email'
- [ ] Must include a send button
- [ ] Must include alt text for the image
- [ ] Bonus: have anchor links change on hover, or change the cursor
- [ ] Deploy to GitHub pages
